### ISSUE TITLE
How to specify a port in the subscription URL?

### ISSUE THREAD

**Issue by jenskutilek** [typeworld/typeworld#10]
My local development server runs at `http://localhost:8080/typeworld/index.json`, how would I specify the port in the typeworld subscription API? I tried `typeworld://json+http//localhost:8080/typeworld/index.json`, but that only gives me a HTTP Error 404 message in the GUI app.

**Comment by yanone** [comment]
I don't have a development server running, but I just checked with a normal API Endpoint that's online, specifying the port with `:443` like your notation, and connected without problems. So I'm not sure what to do here.

**Comment by jenskutilek** [comment]
Hm, weird. Still doesn't work for me.

**Comment by yanone** [comment]
Okay, I'll give this another look. I need to set up a local server first. Honestly, I just tried my online server with :443 for the port, which worked. I'll get back to this.

**Comment by yanone** [comment]
I definitely confirmed now that a URL such as `typeworld://json+http//localhost:8080/typeworld/index.json` works by setting up simple server that serves a flat/all-in-one subscription. The only thing is that you need to serve POST commands, but the error would have been `405` for the wrong request type anyway.
So the only thing I can think of is a nameserver issue where the app can't reach `localhost`. I used `0.0.0.0` successfully, so it's not a port issue. 
I'm closing this.
