### ISSUE TITLE
API command processing may be underdefined

### ISSUE THREAD

**Issue by jenskutilek** [typeworld/typeworld#9]
The description on https://type.world/developer reads:

> This combination installFonts,installableFonts and uninstallFonts,installableFonts will be requested by the app when installing or uninstalling protected fonts. As the seat allowance is expected to change for installing/uninstalling protected fonts, the subscription needs to be updated directly after installing/uninstalling a font for updated display to the user. All requested commands will be nested inside a root command. It is mandatory to execute the commands on the server side in the order they were requested in: First the fonts are served or marked as deleted (installFonts or uninstallFonts), then the updated subscription is generated (installableFonts).

It leaves me wondering if the given command combinations are the only ones that are ever sent by the app, or if the server must be able to handle arbitrary combinations in any order. For example, multiple installFonts or uninstallFonts commands in one request might be conceivable even if it doesn't make sense because there is only one list of fonts to act upon supplied in one request.

If the list of command combinations given in the example is exhaustive, the spec should probably say so explicitly.

**Comment by yanone** [comment]
Needs to be able to handle arbitrary combinations. I’ll clarify it.

**Comment by yanone** [comment]
Added this sentence to the paragraph for clarification:

> An **arbitrary combination** of requested commands must be expected, so plan your code execution accordingly.
